services:
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init-user-db.sql"
    environment:
      POSTGRES_PASSWORD: super_secret_strong_password
      POSTGRES_USER: postgres