spring.application.name: wayd-backend
server:
  port: 8765
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wayd?currentSchema=app
    username: wayd
    password: super_secret_strong_password
  flyway:
    user: wayd
    password: super_secret_strong_password
    url: jdbc:postgresql://localhost:5432/wayd
    locations: classpath:db/postgres/migration
    default-schema: app
    placeholders:
      schema: app
  jpa:
    properties:
      hibernate:
        default_schema: app
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

logging.level.org.springframework.web: DEBUG

cors:
  allowedOrigins:
    - "http://localhost:5173"
